# mcMMOAction config

# A notification soun if the mcMMO message will be displayed into the action bar slot
notificaiton-sound:
    enabled: false

    # A list of all available sounds can be accessed here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    type: ORB_PICKUP
    # This a decimal number from 0 to 1 - it stands for a percent value
    volume: 0.2
    # Here stands 0.63 for 100% - a special case in minecraft
    pitch: 0.1

# What messages should be ignored by this plugin.
# Theses messages will be displayed in the normal chat window
ignore:
    # Skill levelup messages
    levelup: false
    # Tool raise or lower like **YOU LOWER YOUR SHOVEL**
    tool: false
    # Primary abilities like **TREE FELLER ACTIVATED**
    ability: false
    # Too tired messages for the primary ability -> You are too tired to use that ability again. ({0}s)
    tooTired: false
    # A collection of some short hardcore messages including "You have lost {0} levels from death."
    # or Vampire success and failure messages
    hardcore: false
    # Explicit ignore specific messages by adding the message key here
    # For example this makes it possible to show all levelup messages in the action except for excavation

    # Furthermore messages are added if the message ends with '**' - It looks like these message are inteded to be
    # a notification

    # You can see all messages with it's keys here:
    # https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/locale/locale_en_US.properties
    others:
        - Ability.Generic.Refresh