# mcMMOAction config

# A notification soun if the mcMMO message will be displayed into the action bar slot
notificaiton-sound:
    enabled: false

    # A list of all available sounds can be accessed here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    type: ORB_PICKUP
    # This a decimal number from 0 to 1 - it stands for a percent value
    volume: 0.2
    # Here stands 0.63 for 100% - a special case in minecraft
    pitch: 0.1